-- phpMyAdmin SQL Dump
-- version 4.5.2
-- http://www.phpmyadmin.net
--
-- Client :  127.0.0.1
-- Généré le :  Mar 02 Août 2016 à 14:06
-- Version du serveur :  5.7.9
-- Version de PHP :  5.6.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `cwu_bdd`
--

-- --------------------------------------------------------

--
-- Structure de la table `fiches`
--

DROP TABLE IF EXISTS `fiches`;
CREATE TABLE IF NOT EXISTS `fiches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cid` int(11) NOT NULL,
  `prenom` varchar(255) NOT NULL,
  `nom` varchar(255) NOT NULL,
  `ployaute` int(11) NOT NULL,
  `desc_phys` text NOT NULL,
  `observation` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=46 DEFAULT CHARSET=latin1;

--
-- Contenu de la table `fiches`
--

INSERT INTO `fiches` (`id`, `cid`, `prenom`, `nom`, `ployaute`, `desc_phys`, `observation`) VALUES
(2, 11213, 'John', 'Doe', 20, '', '121'),
(4, 69696, 'Steeve', 'Thibodeau', 100, '', 'aw'),
(5, 12212, 'Â«af', 'Afaf', 0, 'N/A', 'N/A'),
(45, 12342, 'Agag', 'Agga', -20, 'N/A', 'N/A'),
(9, 2121, 'Yolo', 'Papa', 0, '', ''),
(10, 131, 'Afaf', 'Aa', 0, '', 'N/A'),
(11, 2424, 'Sgts', 'Sgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis elementum ante. Nulla fringilla libero quis libero ultricies dapibus. Phasellus lacinia sapien a mauris sagittis, quis placerat lacus semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce convallis dui et ante imperdiet congue. Vivamus viverra, neque id sodales elementum, massa eros dapibus justo, finibus vestibulum arcu ipsum ut massa. Sed vestibulum maximus nunc, quis finibus enim tempor vitae. Sed massa risus, faucibus ut feugiat nec, fermentum varius orci. Proin in mattis orci. Nunc mollis quam purus, at elementum neque ultricies eu. Curabitur fringilla erat vel elit ullamcorper molestie. Donec ornare a nunc efficitur tempor.'),
(12, 2424, 'Sgts', 'Sgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis elementum ante. Nulla fringilla libero quis libero ultricies dapibus. Phasellus lacinia sapien a mauris sagittis, quis placerat lacus semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce convallis dui et ante imperdiet congue. Vivamus viverra, neque id sodales elementum, massa eros dapibus justo, finibus vestibulum arcu ipsum ut massa. Sed vestibulum maximus nunc, quis finibus enim tempor vitae. Sed massa risus, faucibus ut feugiat nec, fermentum varius orci. Proin in mattis orci. Nunc mollis quam purus, at elementum neque ultricies eu. Curabitur fringilla erat vel elit ullamcorper molestie. Donec ornare a nunc efficitur tempor.'),
(13, 2424, 'Sgts', 'Sgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis elementum ante. Nulla fringilla libero quis libero ultricies dapibus. Phasellus lacinia sapien a mauris sagittis, quis placerat lacus semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce convallis dui et ante imperdiet congue. Vivamus viverra, neque id sodales elementum, massa eros dapibus justo, finibus vestibulum arcu ipsum ut massa. Sed vestibulum maximus nunc, quis finibus enim tempor vitae. Sed massa risus, faucibus ut feugiat nec, fermentum varius orci. Proin in mattis orci. Nunc mollis quam purus, at elementum neque ultricies eu. Curabitur fringilla erat vel elit ullamcorper molestie. Donec ornare a nunc efficitur tempor.'),
(14, 2424, 'Sgts', 'Sgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis elementum ante. Nulla fringilla libero quis libero ultricies dapibus. Phasellus lacinia sapien a mauris sagittis, quis placerat lacus semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce convallis dui et ante imperdiet congue. Vivamus viverra, neque id sodales elementum, massa eros dapibus justo, finibus vestibulum arcu ipsum ut massa. Sed vestibulum maximus nunc, quis finibus enim tempor vitae. Sed massa risus, faucibus ut feugiat nec, fermentum varius orci. Proin in mattis orci. Nunc mollis quam purus, at elementum neque ultricies eu. Curabitur fringilla erat vel elit ullamcorper molestie. Donec ornare a nunc efficitur tempor.'),
(15, 2424, 'Sgts', 'Sgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis elementum ante. Nulla fringilla libero quis libero ultricies dapibus. Phasellus lacinia sapien a mauris sagittis, quis placerat lacus semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce convallis dui et ante imperdiet congue. Vivamus viverra, neque id sodales elementum, massa eros dapibus justo, finibus vestibulum arcu ipsum ut massa. Sed vestibulum maximus nunc, quis finibus enim tempor vitae. Sed massa risus, faucibus ut feugiat nec, fermentum varius orci. Proin in mattis orci. Nunc mollis quam purus, at elementum neque ultricies eu. Curabitur fringilla erat vel elit ullamcorper molestie. Donec ornare a nunc efficitur tempor.'),
(16, 2424, 'Sgts', 'Sgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis elementum ante. Nulla fringilla libero quis libero ultricies dapibus. Phasellus lacinia sapien a mauris sagittis, quis placerat lacus semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce convallis dui et ante imperdiet congue. Vivamus viverra, neque id sodales elementum, massa eros dapibus justo, finibus vestibulum arcu ipsum ut massa. Sed vestibulum maximus nunc, quis finibus enim tempor vitae. Sed massa risus, faucibus ut feugiat nec, fermentum varius orci. Proin in mattis orci. Nunc mollis quam purus, at elementum neque ultricies eu. Curabitur fringilla erat vel elit ullamcorper molestie. Donec ornare a nunc efficitur tempor.'),
(17, 1234556, 'Adada', 'Ada', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.\r\n\r\nCras mattis faucibus arcu, sit amet feugiat est porttitor sed. Nulla facilisi. Duis consequat magna in orci molestie porta. Cras quis tempus nulla, non venenatis enim. Praesent ac ante quis enim sodales posuere. Nunc aliquam facilisis orci, nec placerat purus. Duis ac cursus est, at mattis sapien. Phasellus faucibus sem id rutrum fermentum. Etiam pellentesque neque ut nunc finibus, quis placerat quam elementum. Suspendisse commodo viverra magna, non vulputate orci mollis vitae. Sed sit amet nibh sit amet magna commodo rhoncus. Sed semper eros a laoreet euismod. Sed a tempor tortor. Vivamus cursus metus sed felis efficitur laoreet. Integer aliquam nisi in sagittis iaculis.'),
(18, 1234556, 'Adada', 'Ada', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.\r\n\r\nCras mattis faucibus arcu, sit amet feugiat est porttitor sed. Nulla facilisi. Duis consequat magna in orci molestie porta. Cras quis tempus nulla, non venenatis enim. Praesent ac ante quis enim sodales posuere. Nunc aliquam facilisis orci, nec placerat purus. Duis ac cursus est, at mattis sapien. Phasellus faucibus sem id rutrum fermentum. Etiam pellentesque neque ut nunc finibus, quis placerat quam elementum. Suspendisse commodo viverra magna, non vulputate orci mollis vitae. Sed sit amet nibh sit amet magna commodo rhoncus. Sed semper eros a laoreet euismod. Sed a tempor tortor. Vivamus cursus metus sed felis efficitur laoreet. Integer aliquam nisi in sagittis iaculis.'),
(19, 1234556, 'Adada', 'Ada', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.\r\n\r\nCras mattis faucibus arcu, sit amet feugiat est porttitor sed. Nulla facilisi. Duis consequat magna in orci molestie porta. Cras quis tempus nulla, non venenatis enim. Praesent ac ante quis enim sodales posuere. Nunc aliquam facilisis orci, nec placerat purus. Duis ac cursus est, at mattis sapien. Phasellus faucibus sem id rutrum fermentum. Etiam pellentesque neque ut nunc finibus, quis placerat quam elementum. Suspendisse commodo viverra magna, non vulputate orci mollis vitae. Sed sit amet nibh sit amet magna commodo rhoncus. Sed semper eros a laoreet euismod. Sed a tempor tortor. Vivamus cursus metus sed felis efficitur laoreet. Integer aliquam nisi in sagittis iaculis.'),
(20, 234, 'Adada', 'Adadad', 0, '', 'Bonjour'),
(21, 525255, 'Ada', 'Adada', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.'),
(22, 525255, 'Ada', 'Adada', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.'),
(23, 12314, 'Adfafaf', 'Afaf', 0, '', 'Bonjour'),
(24, 442, 'Afaf', 'Zfzf', 0, '', 'rLorem ipsum dolor sit amet, cons'),
(25, 141, 'Afaf', 'Afaf', 0, '', 'Lorem ipsum dolor sit amet,'),
(26, 141, 'Afaf', 'Afaf', 0, '', 'Lorem ipsum dolor sit amet,'),
(27, 141, 'Afaf', 'Afaf', 0, '', 'Lorem ipsum dolor sit amet,'),
(28, 1112, 'David', 'Seallow', 100, 'Bau&lt;br/&gt;\ntest2&lt;br/&gt;', 'test&lt;br/&gt;\nhell0'),
(29, 141415, 'Afafaf', 'Sdgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.'),
(30, 141415, 'Afafaf', 'Sdgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.'),
(31, 141415, 'Afafaf', 'Sdgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.'),
(32, 141415, 'Afafaf', 'Sdgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.'),
(33, 141415, 'Afafaf', 'Sdgsg', 0, '', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus mattis dictum augue et pellentesque. Praesent quis mauris euismod diam vestibulum cursus in non magna. Phasellus velit sapien, faucibus at vestibulum sit amet, aliquet sed lectus. Donec ut faucibus elit. Mauris at dui ornare, efficitur nisi id, efficitur justo. Ut mollis felis et metus suscipit, sed scelerisque erat ultricies. Mauris aliquet a sem nec vestibulum. Proin condimentum cursus metus, tempor ultrices sem viverra et. Maecenas ultrices ultricies mauris ut blandit.\r\n\r\nSed gravida aliquam turpis eu pharetra. Ut vestibulum massa vitae turpis ullamcorper dapibus. Nullam felis nulla, luctus sit amet neque ac, porttitor venenatis sapien. Vestibulum odio turpis, lacinia id nisi quis, porta luctus elit. Sed sit amet fringilla nisi, vitae iaculis velit. Mauris sed velit et magna lobortis molestie vitae eget augue. Etiam nec mauris consequat, eleifend urna vel, placerat magna. Maecenas nec lectus augue. Phasellus eu mauris vehicula, fermentum tortor ac, tincidunt nibh. Vivamus accumsan ex id nisi feugiat vestibulum. Proin eget turpis nec nulla tincidunt eleifend in sed erat. Quisque id risus sagittis, consequat sapien eu, volutpat ipsum. Praesent vel malesuada nisl.\r\n\r\nVestibulum viverra cursus lacinia. Suspendisse tempus mauris at imperdiet auctor. Morbi hendrerit pretium purus in interdum. Donec non tincidunt odio. Vestibulum sollicitudin lacinia ligula vitae sollicitudin. Aenean dolor nunc, ultrices fermentum mollis in, faucibus eget nisl. Curabitur faucibus nunc ac consequat ultricies. Quisque ultricies, quam tempor faucibus tincidunt, lectus turpis efficitur mi, nec eleifend augue elit cursus augue. Nullam porttitor, massa eu luctus venenatis, ligula urna tristique urna, sit amet tempor odio neque ut nisl. Donec ac ante tortor. Vivamus ac ligula odio. Sed cursus lacinia massa ac facilisis. Curabitur enim ex, vestibulum ac posuere sit amet, tristique id sem.'),
(34, 34567, 'Goeage', 'Russel', 0, 'N/A', 'Respecte bien le rp et le pain rp'),
(35, 34567, 'Goeage', 'Russel', 0, 'N/A', 'Respecte bien le rp et le pain rp'),
(36, 34567, 'Goeage', 'Russel', 0, 'N/A', 'Respecte bien le rp et le pain rp'),
(37, 34567, 'Goeage', 'Russel', 0, 'N/A', 'Respecte bien le rp et le pain rp'),
(38, 34567, 'Goeage', 'Russel', 0, 'N/A', 'Respecte bien le rp et le pain rp'),
(39, 34567, 'Goeage', 'Russel', 0, 'N/A', 'Respecte bien le rp et le pain rp'),
(40, 34567, 'Goeage', 'Russel', 0, 'N/A', 'Respecte bien le rp et le pain rp'),
(41, 123566, 'Joey', 'Campbell', 50, 'Cehveux brun,&lt;br/&gt;\r\nDent jaunes,&lt;br/&gt;', 'Bon rp, &lt;/br&gt;'),
(42, 123566, 'Joey', 'Campbell', 50, 'Cehveux brun,&lt;br/&gt;\r\nDent jaunes,&lt;br/&gt;', 'Bon rp, &lt;/br&gt;'),
(43, 325, 'Jhonny', 'Campbel', 0, 'N/A', 'N/A'),
(44, 14142, 'Steeve', 'Mathias', 0, 'N/A', 'N/A');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
